### PR TITLE
Changes for consumer rewrite to queue-proc.

### PR DESCRIPTION
**Pull request by stdarg**
@dylanbathurst, the ObjectID references in the mongo code weren't available. Was I mis-using the code? If so, I couldn't figure out how.

### CODE REVIEW

**Comment by dylanbathurst** [comment]
looks good, saw you put async in the package.json but didn't reference it anywhere? Think you could bump the version in the package.json as well and make sure all the apps that use databox pull in the correct version and/or work with the newest version?

**Comment by stdarg** [comment]
async is referenced in ./lib/databox.js  on line 380, the ref has been since 8/5/14.

Will bump! Great way to do it is with:

npm version patch

Which also tags the branch with the npm module version.

**Comment by stdarg** [comment]
And thanks for the comments!

**Comment by stdarg** [comment]
Merging this with git flow.

**Pull request closed without merging**
